name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  APP_NAME_FRONTEND: appsfourneau
  APP_NAME_BACKEND: backendsfourneau

jobs:

  build-deploy-frontend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Deploying Frontend...
        run: docker login -u _ -p ${{ secrets.HEROKU_API_KEY }} registry.heroku.com;
             docker build --file=frontend/frontend.dockerfile --rm=true -t registry.heroku.com/${{ env.APP_NAME_FRONTEND }}/web .;
             docker push registry.heroku.com/${{ env.APP_NAME_FRONTEND }}/web;
             docker run -e HEROKU_API_KEY=${{ secrets.HEROKU_API_KEY }} wingrunr21/alpine-heroku-cli:latest container:release web -a ${{ env.APP_NAME_FRONTEND }};
             echo "Frontend Deployment Complete!"

  build-backend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Build with Gradle
        uses: gradle/gradle-build-action@0d13054264b0bb894ded474f08ebb30921341cee
        with:
          arguments: build
          build-root-directory: backend/
      - uses: actions/upload-artifact@v3
        with:
          name: app
          path: backend/build/libs

  deploy-backend:
    runs-on: ubuntu-latest
    needs: build-backend

    steps:
      - uses: actions/checkout@v3
      - name: Download production artifacts
        uses: actions/download-artifact@v3
        with:
          name: app
          path: backend/build/libs
      - name: Deploying Backend...
        run: docker login -u _ -p ${{ secrets.HEROKU_API_KEY }} registry.heroku.com;
             docker build --file=backend/backend.dockerfile --rm=true -t registry.heroku.com/${{ env.APP_NAME_BACKEND }}/web .;
             docker push registry.heroku.com/${{ env.APP_NAME_BACKEND }}/web;
             docker run -e HEROKU_API_KEY=${{ secrets.HEROKU_API_KEY }} wingrunr21/alpine-heroku-cli:latest container:release web -a ${{ env.APP_NAME_BACKEND }};
             echo "Backend Deployment Complete!"
